#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v10
# autospec commit: 6fa3d52db448
#
Name     : QR-Code-generator
Version  : 1.8.0.cmake3
Release  : 1
URL      : https://github.com/EasyCoding/qrcodegen-cmake/archive/v1.8.0-cmake3/qrcodegen-cmake-1.8.0-cmake3.tar.gz
Source0  : https://github.com/EasyCoding/qrcodegen-cmake/archive/v1.8.0-cmake3/qrcodegen-cmake-1.8.0-cmake3.tar.gz
Source1  : https://github.com/nayuki/QR-Code-generator/archive/v1.8.0/QR-Code-generator-1.8.0.tar.gz
Summary  : @CMAKE_PROJECT_DESCRIPTION@
Group    : Development/Tools
License  : MIT
Requires: QR-Code-generator-lib = %{version}-%{release}
Requires: QR-Code-generator-license = %{version}-%{release}
BuildRequires : buildreq-cmake
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# CMake for the QR-Code-generator
## About
CMake build scripts for the [QR-Code-generator library](https://github.com/nayuki/QR-Code-generator).

%package dev
Summary: dev components for the QR-Code-generator package.
Group: Development
Requires: QR-Code-generator-lib = %{version}-%{release}
Provides: QR-Code-generator-devel = %{version}-%{release}
Requires: QR-Code-generator = %{version}-%{release}

%description dev
dev components for the QR-Code-generator package.


%package lib
Summary: lib components for the QR-Code-generator package.
Group: Libraries
Requires: QR-Code-generator-license = %{version}-%{release}

%description lib
lib components for the QR-Code-generator package.


%package license
Summary: license components for the QR-Code-generator package.
Group: Default

%description license
license components for the QR-Code-generator package.


%prep
%setup -q -n qrcodegen-cmake-1.8.0-cmake3
cd %{_builddir}
tar xf %{_sourcedir}/QR-Code-generator-1.8.0.tar.gz
cd %{_builddir}/qrcodegen-cmake-1.8.0-cmake3
mkdir -p ./
cp -r %{_builddir}/QR-Code-generator-1.8.0/* %{_builddir}/qrcodegen-cmake-1.8.0-cmake3/./

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1716919037
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DBUILD_TESTS=ON
make  %{?_smp_mflags}
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
cd clr-build; make test

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1716919037
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/QR-Code-generator
cp %{_builddir}/qrcodegen-cmake-1.8.0-cmake3/LICENSE %{buildroot}/usr/share/package-licenses/QR-Code-generator/553d91f08e9560f03f864a90abd7fb59dad68cb3 || :
export GOAMD64=v2
GOAMD64=v2
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/qrcodegen/qrcodegen.h
/usr/include/qrcodegencpp/qrcodegen.hpp
/usr/lib64/cmake/qrcodegen/qrcodegen-config-version.cmake
/usr/lib64/cmake/qrcodegen/qrcodegen-config.cmake
/usr/lib64/cmake/qrcodegen/qrcodegen-targets-relwithdebinfo.cmake
/usr/lib64/cmake/qrcodegen/qrcodegen-targets.cmake
/usr/lib64/cmake/qrcodegencpp/qrcodegencpp-config-version.cmake
/usr/lib64/cmake/qrcodegencpp/qrcodegencpp-config.cmake
/usr/lib64/cmake/qrcodegencpp/qrcodegencpp-targets-relwithdebinfo.cmake
/usr/lib64/cmake/qrcodegencpp/qrcodegencpp-targets.cmake
/usr/lib64/libqrcodegen.so
/usr/lib64/libqrcodegencpp.so
/usr/lib64/pkgconfig/qrcodegen.pc
/usr/lib64/pkgconfig/qrcodegencpp.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libqrcodegen.so.1
/usr/lib64/libqrcodegen.so.1.8.0
/usr/lib64/libqrcodegencpp.so.1
/usr/lib64/libqrcodegencpp.so.1.8.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/QR-Code-generator/553d91f08e9560f03f864a90abd7fb59dad68cb3
